#!/bin/bash

# 硬负样本挖掘YOLO训练使用示例
# 展示如何使用 --project 和 --name 参数

echo "🚀 硬负样本挖掘YOLO训练示例"
echo "================================"

# 示例1: 基本使用（自动生成名称）
echo "📝 示例1: 基本使用（自动生成名称）"
echo "python3 detection/train_yolo_with_hard_negative.py \\"
echo "    --data ./datasets/dataset.yaml \\"
echo "    --model yolov8s.pt \\"
echo "    --epochs 100 \\"
echo "    --project runs/train \\"
echo "    --mining_strategy confidence_based \\"
echo "    --hard_negative_ratio 0.3"
echo ""

# 示例2: 指定实验名称
echo "📝 示例2: 指定实验名称"
echo "python3 detection/train_yolo_with_hard_negative.py \\"
echo "    --data ./datasets/dataset.yaml \\"
echo "    --model yolov8s.pt \\"
echo "    --epochs 100 \\"
echo "    --project runs/train \\"
echo "    --name fish_detection_hard_negative_$(date +%Y%m%d_%H%M%S) \\"
echo "    --mining_strategy confidence_based \\"
echo "    --hard_negative_ratio 0.3 \\"
echo "    --confidence_threshold 0.6 \\"
echo "    --save_hard_negatives"
echo ""

# 示例3: 使用不同的挖掘策略
echo "📝 示例3: 使用不同的挖掘策略"
echo "python3 detection/train_yolo_with_hard_negative.py \\"
echo "    --data ./datasets/dataset.yaml \\"
echo "    --model yolov8s.pt \\"
echo "    --epochs 150 \\"
echo "    --project runs/train \\"
echo "    --name iou_based_mining_$(date +%Y%m%d_%H%M%S) \\"
echo "    --mining_strategy iou_based \\"
echo "    --hard_negative_ratio 0.4 \\"
echo "    --iou_threshold 0.6"
echo ""

# 示例4: 完整参数配置
echo "📝 示例4: 完整参数配置"
echo "python3 detection/train_yolo_with_hard_negative.py \\"
echo "    --data ./datasets/dataset.yaml \\"
echo "    --model yolov8s.pt \\"
echo "    --epochs 200 \\"
echo "    --batch 32 \\"
echo "    --imgsz 640 \\"
echo "    --device 0 \\"
echo "    --project runs/train \\"
echo "    --name comprehensive_hard_negative_$(date +%Y%m%d_%H%M%S) \\"
echo "    --mining_strategy confidence_based \\"
echo "    --hard_negative_ratio 0.3 \\"
echo "    --confidence_threshold 0.5 \\"
echo "    --iou_threshold 0.5 \\"
echo "    --save_hard_negatives \\"
echo "    --lr0 0.01 \\"
echo "    --patience 50 \\"
echo "    --workers 8"
echo ""

# 示例5: 与原始train_yolo.py对比
echo "📝 示例5: 与原始train_yolo.py对比"
echo ""
echo "原始训练脚本:"
echo "python3 detection/train_yolo.py \\"
echo "    --data ./datasets/dataset.yaml \\"
echo "    --model yolov8s.pt \\"
echo "    --epochs 100 \\"
echo "    --project runs/train \\"
echo "    --name single_yolov8s_\$(date +%Y%m%d_%H%M%S)"
echo ""
echo "硬负样本挖掘版本:"
echo "python3 detection/train_yolo_with_hard_negative.py \\"
echo "    --data ./datasets/dataset.yaml \\"
echo "    --model yolov8s.pt \\"
echo "    --epochs 100 \\"
echo "    --project runs/train \\"
echo "    --name single_yolov8s_hard_negative_\$(date +%Y%m%d_%H%M%S) \\"
echo "    --mining_strategy confidence_based \\"
echo "    --hard_negative_ratio 0.3"
echo ""

echo "🎯 参数说明:"
echo "  --project: 输出项目目录，用于组织实验结果"
echo "  --name: 实验名称，如果不指定会自动生成"
echo "  --mining_strategy: 硬负样本挖掘策略 (confidence_based, iou_based, loss_based)"
echo "  --hard_negative_ratio: 硬负样本比例 (0.0-1.0)"
echo "  --confidence_threshold: 置信度阈值 (0.0-1.0)"
echo "  --iou_threshold: IoU阈值 (0.0-1.0)"
echo "  --save_hard_negatives: 保存硬负样本到文件"
echo ""

echo "📁 输出结构:"
echo "  runs/train/"
echo "  ├── {experiment_name}/"
echo "  │   ├── weights/           # 训练好的模型权重"
echo "  │   ├── results.png        # 训练结果图表"
echo "  │   ├── confusion_matrix.png"
echo "  │   ├── hard_negative_report.json  # 硬负样本挖掘报告"
echo "  │   └── hard_negatives/    # 硬负样本文件（如果启用）"
echo "  │       ├── images/"
echo "  │       └── annotations/"
echo ""

echo "✅ 使用建议:"
echo "1. 使用有意义的实验名称，包含日期和策略信息"
echo "2. 根据数据集特点调整挖掘参数"
echo "3. 定期检查硬负样本挖掘报告"
echo "4. 比较不同策略的效果"
echo "5. 使用 --save_hard_negatives 保存困难样本用于分析"

